# Project Configuration
project:
  name: "Rowing Pose Detection Analyser"
  version: "1.1.1"

# Directories Configuration
directories:
  data: "data"
  src: "src"
  config: "src/config"
  sessions: "sessions"


# Logging Configuration
logging:
  handlers:
    - sink: stdout
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <level>{message}</level>"
      level: INFO
      colorize: true

# ProcessLandmarks Configuration
landmarks:
  mapping:
    ear: 8
    shoulder: 12
    elbow: 14
    wrist: 16
    hand: 20
    hip: 24
    knee: 26
    ankle: 28
  connections:
    - [ ear, shoulder ]
    - [ shoulder, elbow ]
    - [ elbow, wrist ]
    - [ wrist, hand ]
    - [ shoulder, hip ]
    - [ hip, knee ]
    - [ knee, ankle ]

# Video Input Criteria
video:
  format: "mp4"
  min_duration: 5
  max_duration: 300
  fps: 30
  width: 1920
  height: 1080

# Default values for session
session:
  files:
    session_config: "session_config.json"
    raw_video: "raw.mp4"
    landmark_data: "landmarks.yaml"
    analysis_data: "scripts.yaml"
    annotated_video: "annotated.mp4"

  annotation_preferences:
    opacity: 0.8

    bone_colour: [ 250, 144, 30 ]
    bone_thickness: 4

    landmark_colour: [139, 61, 72]
    landmark_radius: 5

    reference_line_length: 96
    reference_line_colour: [255, 255, 255]
    reference_line_thickness: 3
    reference_line_dash_factor: 8

  mediapipe_preferences:
    model_complexity: 2
    smooth_landmarks: true
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
