# Project Configuration
project:
  name: "Rowing Pose Detection Analyser"
  version: "1.0.0"

# Directories Configuration
dir:
  data: "data"
  src: "src"
  config: "src/config"
  analyses: "analyses"

# Video Input Criteria
video:
  format: ".mp4"
  min_duration: 5
  max_duration: 300
  fps: 30

# Logging Configuration
logging:
  handlers:
    - sink: stdout
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <level>{message}</level>"
      level: INFO
      colorize: true

