# Project Configuration
project:
  name: "Rowing Pose Detection Analyser"
  version: "1.0.0"

# Directories Configuration
dir:
  data: "data"
  src: "src"
  config: "src/config"
  sessions: "sessions"

session_dir:
  raw_video_path: "raw.mp4"
  annotated_video_path: "annotated.mp4"
  landmark_data_path: "landmark.yaml"
  session_config_path: "session_config.json"

# Video Input Criteria
video:
  format: "mp4"
  min_duration: 5
  max_duration: 300
  fps: 30
  width: 1920
  height: 1080

# Logging Configuration
logging:
  handlers:
    - sink: stdout
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <level>{message}</level>"
      level: INFO
      colorize: true

# ProcessLandmarks Configuration
landmarks:
  mapping:
    ear: 8
    shoulder: 12
    elbow: 14
    wrist: 16
    hand: 20
    hip: 24
    knee: 26
    ankle: 28
  connections:
    - [ear, shoulder]
    - [shoulder, elbow]
    - [elbow, wrist]
    - [wrist, hand]
    - [shoulder, hip]
    - [hip, knee]
    - [knee, ankle]

# Annotation Configuration
annotation_prefs:
  landmark:
    colour: [139, 61, 72]
    radius: 5
  bone:
    colour: [250, 144, 30]
    thickness: 4
  reference_line:
    length: 96
    colour: [255, 255, 255]
    thickness: 3
    dash_factor: 8
  opacity: 1

# Mediapipe Configuration
mediapipe:
  model_complexity: 0
  smooth_landmarks: true
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
